export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const TOKEN_REFRESHED = 'TOKEN_REFRESHED';

export const APIARY_LIST_RECEIVED = 'APIARY_LIST_RECEIVED';
export const APIARY_RECEIVED = 'APIARY_RECEIVED';
export const APIARY_CREATED = 'APIARY_CREATED';